backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "journal"
    label: "Journal"
    folder: "src/pages/journal/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "journal-post",
        }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - {
          label: Category,
          name: category,
          widget: select,
          options: [Thoughts, "Startup Story", Press, Sandbox, Events],
        }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Heading, name: heading, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - { label: Introduction, name: introduction, widget: text }
      - { label: Body, name: body, widget: markdown }

  - name: "ventures"
    label: "Ventures"
    folder: "src/pages/ventures/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "ventures-post",
        }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Company, name: company, widget: string }
      - { label: Logo, name: logo, widget: string }
      - { label: Video, name: video, widget: file, required: false }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Heading, name: heading, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - { label: Introduction, name: introduction, widget: text }
      - {
          label: Participants,
          name: participants,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: Image, name: image, widget: image },
              { label: Title, name: title, widget: string },
            ],
        }
      - {
          label: Links,
          name: links,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              {
                label: Category,
                name: category,
                widget: select,
                options:
                  [
                    Website,
                    Facebook,
                    Linkedin,
                    Twitter,
                    Instagram,
                    Pinterest,
                    Youtube,
                  ],
              },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Focus,
              name: focus,
              widget: list,
              allow_add: false,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Link, name: link, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: "Hover Image", name: hover, widget: image },
                ],
            }
          - { label: Intro, name: intro, widget: text }
          - {
              label: Process,
              name: process,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Steps,
                    name: steps,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        {
                          label: Icon,
                          name: icon,
                          widget: select,
                          options: [absorb, concept, create, learn],
                        },
                        { label: Description, name: description, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Slider,
              name: slider,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Quote, name: quote, widget: text },
                  {
                    label: Logo,
                    name: logo,
                    widget: file,
                    allow_multiple: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Intro, name: intro, widget: text }
          - {
              label: Mission,
              name: mission,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Sections,
                    name: sections,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Body, name: body, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Values,
              name: values,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Values,
                    name: values,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Body, name: body, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Team,
              name: team,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: People,
                    name: people,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: Photo, name: photo, widget: image },
                        { label: Large, name: large, widget: boolean },
                      ],
                  },
                ],
            }
          - {
              label: Action,
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Pages,
                    name: pages,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                        { label: Link, name: link, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Intro, name: intro, widget: text }
          - {
              label: "Contact Type",
              name: type,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: "Contact Types",
                    name: types,
                    widget: list,
                    fields:
                      [
                        { label: Name, name: name, widget: string },
                        { label: "Embed Code", name: embed, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Social,
              name: social,
              widget: object,
              fields: [{ label: Heading, name: heading, widget: string }],
            }
          - { label: Map, name: map, widget: image }
          - {
              label: Locations,
              name: locations,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Addresses,
                    name: addresses,
                    widget: list,
                    fields:
                      [
                        { label: Address, name: address, widget: text },
                        { label: Number, name: number, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/journal/index.md"
        label: "Journal"
        name: "journal"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "journal-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Action,
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Pages,
                    name: pages,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                        { label: Link, name: link, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: "src/pages/experiments/index.md"
        label: "Lab Experiments"
        name: labExperiments
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "experiments-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Action,
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Pages,
                    name: pages,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                        { label: Link, name: link, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: "src/pages/experiments/enterprise.md"
        label: "Enterprise Experiments"
        name: enterpriseExperiments
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "experiments-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Action,
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Pages,
                    name: pages,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                        { label: Link, name: link, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: "src/pages/ventures/index.md"
        label: "Ventures"
        name: ventures
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "ventures-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Action,
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Pages,
                    name: pages,
                    widget: list,
                    allow_add: false,
                    fields:
                      [
                        { label: Title, name: title, widget: string },
                        { label: Description, name: description, widget: text },
                        { label: Link, name: link, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                ],
            }
      - file: "src/pages/network/index.md"
        label: "Network"
        name: "network"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "network-page",
            }
          - { label: Section, name: section, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Intro, name: intro, widget: text }
          - {
              label: Partners,
              name: partners,
              widget: list,
              fields:
                [
                  {
                    label: Category,
                    name: category,
                    widget: select,
                    options:
                      [
                        coworking,
                        mentorship,
                        "economic dev",
                        "community contacts",
                      ],
                  },
                  { label: Name, name: name, widget: string },
                  { label: Logo, name: logo, required: false, widget: image },
                  { label: Link, name: link, widget: string },
                ],
            }
