backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "journal"
    label: "Journal"
    folder: "src/pages/journal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "journal-post"}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Category, name: category, widget: select, options: [Thoughts, "Startup Stories", Press, Sandbox, Events]}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Heading, name: heading, widget: string}
      - {label: Subheading, name: subheading, widget: string}
      - {label: Introduction, name: introduction, widget: text}
      - {label: Body, name: body, widget: markdown}

  - name: "ventures"
    label: "Ventures"
    folder: "src/pages/ventures"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ventures-post"}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Company, name: company, widget: string}
      - {label: Logo, name: logo, widget: string}
      - {label: Video, name: video, widget: file, required: false}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Heading, name: heading, widget: string}
      - {label: Subheading, name: subheading, widget: string}
      - {label: Introduction, name: introduction, widget: text}
      - {label: Participants, name: participants, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}]}
      - {label: Links, name: links, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Category, name: category, widget: select, options: [Website, Facebook, Linkedin, Twitter, Instagram, Pinterest]}]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Section, name: section, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Sections, name: sections, widget: list, allow_add: false, fields: [{label: Title, name: title, widget: string}, {label: Icon, name: icon, widget: select, options: [circle, triangle]}, {label: Description, name: description, widget: text}]}, {label: Watermark, name: watermark, widget: string}]}
          - {label: Action, name: action, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Pages, name: pages, widget: list, allow_add: false, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Link, name: link, widget: string}, {label: Image, name: image, widget: image}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
